dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.116.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/sigv4authextension v0.116.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.116.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.116.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.116.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.116.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.116.0
