apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service-python
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: billing-service-python
  template:
    metadata:
      labels:
        io.kompose.service: billing-service-python
      annotations:
        sidecar.opentelemetry.io/inject-python: 'true'
        instrumentation.opentelemetry.io/inject-python: 'true'
    spec:
      serviceAccountName: visits-service-account
      containers:
        - image: 613477150601.dkr.ecr.us-east-1.amazonaws.com/python-petclinic-billing-service:latest
          # securityContext:
          #   runAsNonRoot: true
          #   allowPrivilegeEscalation: true
          name: billing-service-python
          env:
            - name: EUREKA_SERVER_URL
              value: discovery-server
            - name: DB_NAME
              value: 'postgres'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: username
            - name: DB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: password
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: dbinfo
                  key: endpoint
            - name: DATABASE_PROFILE
              value: postgresql
            - name: NOTIFICATION_ARN
              valueFrom:
                secretKeyRef:
                  name: notification
                  key: sns_arn
            - name: REGION
              valueFrom:
                secretKeyRef:
                  name: notification
                  key: region
          # command: ["sh", "-c"]
          # args: ['manage.py', 'runserver', '0.0.0.0:8000']
          command: ['sh', '-c']
          args:
            - |
              python manage.py migrate
              python manage.py runserver 0.0.0.0:8800
          ports:
            - containerPort: 8800
          imagePullPolicy: Always
      restartPolicy: Always
